### ISSUE TITLE
How to Generate Deterministic PDFs with QuestPDF for Consistent Hashing?

### ISSUE THREAD

**Issue by nemec784** [QuestPDF/QuestPDF#1038]
Hello!

I'm using QuestPDF to generate PDF documents and am looking to produce deterministic outputs—where identical input data generates identical PDFs with the same hash values. This is essential for my use case, where we need to verify data integrity by comparing hash values of generated PDFs.

I've noticed that even with the same data, the generated PDFs occasionally differ slightly in their byte structure, leading to different hash values. I suspect this might be due to metadata like creation timestamps or other document info embedded during PDF generation.

Could you suggest any approaches or best practices in QuestPDF to ensure deterministic PDF outputs? Specifically:

1. Is there a way to control or remove metadata (like timestamps) to make the output fully repeatable?

2. Are there any settings or configurations in QuestPDF that can help achieve this?

Any insights on achieving consistent hashing for identical inputs would be greatly appreciated. 
Thanks in advance!

**Comment by nemec784** [comment]
I accidentally selected the wrong label for this issue. Could someone please assist with this? Thank you!

**Comment by MarcinZiabek** [comment]
The primary reason for inconsistent output is the PDF/A flag configurable in DocumentSettings.

Please note that the library output may change over time due to internal optimizations and improvements 😄 

I suggest using the Verify library, which solves this issue by working on images. It is a more stable solution and also provides a better visual comparison. However, the image output may also differ between operation systems. https://www.nuget.org/packages/Verify.QuestPDF

**Comment by nemec784** [comment]
Thank you so much for the detailed guidance!

Disabling the PDF/A flag and setting the same values for CreationDate and ModifiedDate in DocumentMetadata worked perfectly. Now I get the same hash value for identical PDFs upon each regeneration!

Also, thanks for mentioning Verify.QuestPDF! We’ll definitely give it a try for additional verification.

Thanks again for your help!
