### ISSUE TITLE
Background image does not render in Landscape mode

### ISSUE THREAD

**Issue by Cubelaster** [QuestPDF/QuestPDF#1058]
**Describe the bug**
Background image does not render in Landscape mode. 
In portrait mode, same code, works as intended. 

**To Reproduce**
I am trying to draw a table in Landscape mode, for better visibility. 
Previously I had Portrait mode and tried to display rows as 2 rows, creating a complicated grid inside the table. 
Everything worked fine and I was able to put a memorandum on the Background of the Page without an issue, using this code: 
```
    page.Size(PageSizes.A4);
    .
    .
    .
    page.Background()
        .Extend()
        .Decoration(handler =>
        {
            handler.Before().Svg(image);
        });
```

**Expected behavior**
The expected behavior was that a provided .svg image would render in the background, over entire page, just like it does for Portrait mode, where it is still clearly happening.

**Screenshots**
![Untitled](https://github.com/user-attachments/assets/5c1bcf4e-61a3-41fc-a44f-a981a93d4f9f)

You will notice the Portrait page has a background (hidden logo on top and blue info on bottom) which is a single .svg image across the entire page. 
I tried to do the same for second page but nothing is showing. 
Bear in mind, if I use Background Color, it works as expected. 
Only image is not showing. 

**Environment**
What version of the library do you use? 2024.10.2
What operating system do you use? (OS type, x64 vs x86 vs arm64): Win 10/11 (tried on both), x64

**Additional context**

**Comment by MarcinZiabek** [comment]
Could you please share your SVG image? I wonder what aspect ratio does it have?

**Comment by Cubelaster** [comment]
![Memorandum GasOil MEMO - podloga PDF 2 bez bočnog teksta](https://github.com/user-attachments/assets/2852c494-890d-40d5-9f5a-b9a25b60762b)

Does aspect ratio matters for .svgs? 
And what else matters?

**Comment by MarcinZiabek** [comment]
Yes, it does matter, just as it does in any other image format. By default, the library attempts to scale the image so that it fits the available space horizontally. In your case, it is not possible due to aspect ratio.

You can modify this behavior by using the `FitArea` or `FitUnproportionally` APIs. However, this is likely not what you want. 

My suggestion is to split your background image into two parts: a header and a footer. Then, use the `Layers` element to position the header at the top of the page and the footer at the bottom, applying appropriate scaling.

**Comment by MarcinZiabek** [comment]
Please take a look at the general documentation about images, which describes various fit modes: https://www.questpdf.com/api-reference/image.html

Generally speaking, when your images have an aspect ratio of 3:4 and your container has an aspect ratio of 4:3, it is impossible to fit the images into the container in such a way that the entire area is covered without deforming the images. 

The thing that could technically solve your issue is to use context-aware scaling, which is rather an overkill from the QuestPDF perspective: https://helpx.adobe.com/photoshop/using/content-aware-scaling.html
