### ISSUE TITLE
Previewer unable to load generated PDF

### ISSUE THREAD

**Issue by rm-code** [QuestPDF/QuestPDF#172]
**Describe the bug**
When I run a minimal PDF example (Net6 console application inVisual Studio 2022 17.1.3), the previewer starts normally, but stays empty. When I click the magnifier symbo Acrobat Reader says that the file can't be opened because it is broken. Any way to see a stack trace or log?

**To Reproduce**
Create Net6  console application inVisual Studio 2022 17.1.3 with minimal code example:

```csharp
var document = Document.Create(container =>
{
  container.Page(page =>
  {
    page.Header()
    .Text("Test");
  });
});

document.GeneratePdf("test.pdf"); // this works

//document.ShowInPreviewer(); // this doesn't
```

**Expected behavior**
Previewer should display generated PDF.

**Screenshots**
Generated PDF with `GeneratePdf`:
![image](https://user-images.githubusercontent.com/11627131/162224915-f2233847-d0c1-43d2-b574-49c690f761c6.png)

Previewer Output:
![image](https://user-images.githubusercontent.com/11627131/162224750-af7860fc-1ad1-4e73-9ec4-e9c8650f6aaa.png)

**Additional context**
Net6 Console Application in Visual Studio 2022 17.1.3.

**Comment by MarcinZiabek** [comment]
Hello 😁 Thank you for finding this issue. 

Is it possible that your operating system is blocking local HTTP connections on the 12500 port? Please try other ports and check if it does help: `.ShowInPreviewer(12345)`, maybe lower ones like 5000?

**Comment by MarcinZiabek** [comment]
Once you confirm, I can prepare a timeout mechanism that throws an exception in case of a problem with communication.

**Comment by rm-code** [comment]
>Is it possible that your operating system is blocking local HTTP connections on the 12500 port? Please try other ports and check if it does help: .ShowInPreviewer(12345), maybe lower ones like 5000?

Hi Marcin, 
I tried different ports, but the outcome stays the same. It just gives me a blank Previewer Window.

**Comment by Bebo-Maker** [comment]
Try making a change to your document generation code while running and apply hot reload. Do you see the document now?
I had this issue while testing the initial implementation but thought is was fixed

**Comment by MarcinZiabek** [comment]
Hello 😁 As I don't have any better ideas, I decided to follow my initial concept and prepared [new 2022.4.1 release](https://github.com/QuestPDF/QuestPDF/releases/tag/2022.4.1). 

@rm-code Would you like to update your environment (both library and previewer) and try them?

**Comment by rm-code** [comment]
@MarcinZiabek The exception is displayed as expected on my end. The good news is, that a colleague of mine can run QuestPDF Previewer without issues on his system - so it's some problem on my end 😄

**Comment by MarcinZiabek** [comment]
@gigios Does the preview application open?

**Comment by gigios** [comment]
@MarcinZiabek Yes, the preview application is open without problems, but without show any content.
![immagine](https://user-images.githubusercontent.com/8749627/164986591-1c3b129e-b6bb-466d-b755-e171feed808e.png)

**Comment by gigios** [comment]
> @gigios Does the preview application open?

Sorry, I probably misunderstood the use of the previewer.
I have seen that with the QuestPDF.ExampleInvoce the previewer is open automatically, in my tests I have always started manually the previewer from the command prompt.
Anyway, if I start only my application, when it's executed the instruction ShowInPreviewer() nothing happen, the application seems 'blocked' on the instruction and the previewer view is not shown.

**Comment by MarcinZiabek** [comment]
Thank you for your response and investigation!

> I have seen that with the QuestPDF.ExampleInvoce the previewer is open automatically, in my tests I have always started manually the previewer from the command prompt.

This should not result in any issues. QuestPDF first attempts to detect if the Previewer is already running. If not, the new instance is created.

> Anyway, if I start only my application, when it's executed the instruction ShowInPreviewer() nothing happen, the application seems 'blocked' on the instruction and the previewer view is not shown.

Please make sure that you use the 2022.4.1 version (both library and previewer). If the connection cannot be established within 10 seconds, the `Cannot connect to the QuestPDF Previewer tool.` exception should be thrown. Please check if you get such an exception.

On your screen, I see the TaskCancelledException. Are you able to provide more detailed stack trace of this exception? The more info, the better 😁

**Comment by gigios** [comment]
> Please make sure that you use the 2022.4.1 version (both library and previewer).

I have checked the previewer and the version is: 2022.4.1.0
For the library I confirm that it's also the 2022.4.1 `<PackageReference Include="QuestPDF" Version="2022.4.1" />`

> If the connection cannot be established within 10 seconds, the Cannot connect to the QuestPDF Previewer tool. exception should be thrown. 

I have started the report generation on my application, after one minute I have pressed the 'pause' button of the debugger to check where is the execution.
![image](https://user-images.githubusercontent.com/8749627/165242531-6155368c-de39-4be4-a566-cf8a3b701a5c.png)
As you can see the code is 'blocked' on the instruction `document.ShowInPreviewer();`

> On your screen, I see the TaskCancelledException. Are you able to provide more detailed stack trace of this exception? 

I have reopen the QuestPDF.ExempleInvoice and this is the callstack result of the exception when I have closed the previewer view:
`   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at QuestPDF.Previewer.Extensions.<<ShowInPreviewerAsync>g__WaitForPreviewerExit|1_3>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at QuestPDF.Previewer.Extensions.<ShowInPreviewerAsync>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at QuestPDF.Previewer.Extensions.ShowInPreviewer(IDocument document, Int32 port)
   at QuestPDF.ExampleInvoice.Program.Main(String[] args) in F:\Code\GitHub\PDF\QuestPDF\QuestPDF-ExampleInvoice\Program.cs:line 22`

The exception message is: "A task was canceled."

**Comment by MarcinZiabek** [comment]
OK, the aformentioned `TaskCancelledException` is thrown because the previewer process has exited, maybe because of some issue? 

1) Please download the official repository.
2) Start the `Previewer` project in debug mode.
3) Start the `Previewer.Examples` project in normal mode, without a debugger attached.
4) Observe if any exceptions are thrown.

I am very sorry that this process takes so long. I am trying my best to understand and help, as always `it works for me` 😁

**Comment by gigios** [comment]
> I am very sorry that this process takes so long. I am trying my best to understand and help, as always it works for me 😁

This is a mantra I often say for my software 😂
First of all, thank you for your support time.

This is not a big issue form me, after many task with the real PDF now I have the layout desired 😊

For the test, I have started the previewer in debug, and it's shown the  'empty' view.
I have also started the QuestPDF.ExampleInvoice, with the only change to call the ShowInPreviewer method, without the debugger but it's open a new previewer view empty and the pdf preview is shown in the 'first' view (probably this is normal, I don't know)
The QuestPDF.ExampleInvoice raise the exception without close the previewer.

![image](https://user-images.githubusercontent.com/8749627/165696830-830b9d15-30e4-4acc-b27a-4a92e9ce4578.png)

`Unhandled exception. System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 0.25 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at QuestPDF.Previewer.PreviewerService.RefreshPreview(ICollection`1 pictures)
   at QuestPDF.Previewer.Extensions.ShowInPreviewerAsync(IDocument document, Int32 port)
   at QuestPDF.Previewer.Extensions.ShowInPreviewer(IDocument document, Int32 port)
   at QuestPDF.ExampleInvoice.Program.Main(String[] args) in F:\Code\GitHub\PDF\QuestPDF\QuestPDF-ExampleInvoice\Program.cs:line 22

F:\Code\GitHub\PDF\QuestPDF\QuestPDF-ExampleInvoice\bin\Debug\net6.0\QuestPDF.ExampleInvoice.exe (process 15296) exited with code -532462766.`

**Comment by MarcinZiabek** [comment]
Thanks you! We are getting close 😁

Would you like to modify [this line](https://github.com/QuestPDF/QuestPDF/blob/e54e09de153319c41ee7e63abd7f6a0ea565b39b/QuestPDF/Previewer/PreviewerService.cs#L27) and set it to something significantly higher? E.g. 5 seconds?

This is a timeout of localhost communication between QuestPDF and the Previewer instance. This time is reserved for:
- the localhost HTTP request sent from QuestPDF (your programm) to the Previewer,
- in Previewer: content deserialization (from JSON),
- in Previewer: starting new asynchronous, non-blocking task to update preview. 

On my PC, during testing, this process has never taken more than 100ms, even for huge documents, e.g. 250 pages long with many images. 

Maybe we should consider increasing the timeout for lower-end devices or environments with obtrusive security-related software? If indeed this is a case, would be great to know what minimal timeout wors for you? Maybe you are just slightly passing the threshold?

**Comment by gigios** [comment]
Very fast test, without success.
First I have seen that in the solution of QuestPDF, that I'm using to start the Previewer in debug mode, was not defined NET6_0_OR_GREATER.
With this 'fix' the solution of the QuestPDF.ExampleInvoice the problem still present (also with 5 seconds as timeout).
At this point I had a dubt, the ExampleInvoice was using the nuget version of the library!
I have removed this reference and added directly the project QuestPDF and added to the sample the 'project reference' to the library.
In this way the sample works without exceptions.

I hae  tried the same solution in my project (I have added directly the QuestPDF source code), but the problem related the missing visualization of the Previewer and the 'blocked' app on the method is again available.
If I press the 'pause' button of the debugger, I can see where the code is 'blocked' (in PreviewerExtensions.cs):

![image](https://user-images.githubusercontent.com/8749627/165758298-f62370d8-1e0d-43e9-8138-fdbc214f37ad.png)

**Comment by MarcinZiabek** [comment]
> In this way the sample works without exceptions.

Does it mean that you have been able to make the code running? Would be great to know exactly what has happened. You mentioned several activities and I am not sure if the timeout increase is indeed a solution here, or maybe something else. It is also best to test with the QuestPDF.Previewer.Examples project 😊

**Comment by gigios** [comment]
> Does it mean that you have been able to make the code running? 

Your example yes, my code no!

For me it's not very clear what happen.
I have added some breakpoints in the QuestPDF (imported as source inside my application), and when I try to show the previewer the code check if the previewer is available with the method IsPreviewerAvailable where use the HttpClient instance created in the constructor of the previewer service with the timeout of 250 ms.
What I hae seen is that, in some not clear cases, the timeout seems ignored (the execution stay 'blocked' on the call of:
`var result = await HttpClient.GetAsync("/ping");`
(PS: I have started the previewer in another instance of Visual Studio but is not identified by this check)

In other tests the timeout is raised correctly (I think it's correct 😊) and the code continue with a 'manual' start of the previewer with the method StartPreviewer.
I see the additional previewer view, the code continue with the async method WaitForConnection() where the code is blocked in the:
`await Task.Delay(TimeSpan.FromMilliseconds(250));`

I'm not an expert of the Task and the async/await pattern (this is a my big fault), but seems related this management the problem (and of course some 'limitation' in my PC that does not allow to identify the previewer process).

In the next days I will try to create a small and simple project to investigate better on this problem.
PS: I don't know if the problem is related the localhost connection, because my application is connecting with a local service via localhost ip, but with a different port.

**Comment by MarcinZiabek** [comment]
> Your example yes, my code no!

The aforementioned timeout adjustments you have applied in the library part. Therefore, if you use QuestPDF in another project via the nuget package, they will not be present there. As a result, the adjument may fix the example in the library repository, but does not fix your private project. Does it make sense?

If so, would you like to experiment a bit and try to find the lowest HttpClient timeout value that works for you? When using the example within the library repository.

P.S. I am very sorry for replying so late. There is just a lot of going on in my personal life, very positive yet time-consuming events. I hope tha you understand 😁

**Comment by gigios** [comment]
> P.S. I am very sorry for replying so late. There is just a lot of going on in my personal life, very positive yet time-consuming events. I hope tha you understand 😁

No problem, I understand perfectly 😀, I also have little time to experiment 😊
I will investigate better as soon as possible.

**Comment by sc-csaba** [comment]
It seems if the document reaches a certain size, the connection to the previewer disconnects (2022.5.0, windows)

So I tried to add this line to CommunicationService.Start method:
`builder.WebHost.UseKestrel(options => options.Limits.MaxRequestBodySize = null);`

**Comment by MarcinZiabek** [comment]
> So I tried to add this line to CommunicationService.Start method:
> `builder.WebHost.UseKestrel(options => options.Limits.MaxRequestBodySize = null);`

Has that helped? Would you like to describe your document? Number of pages, type of content?

**Comment by sc-csaba** [comment]
> > So I tried to add this line to CommunicationService.Start method:
> > `builder.WebHost.UseKestrel(options => options.Limits.MaxRequestBodySize = null);`
> 
> Has that helped? Would you like to describe your document? Number of pages, type of content?

I trying with a 13 page PDF (1,273,485 bytes), encoded to multipart/form-data (30,355,162 bytes)

yes, helped.

Before the 'fix' I got
```
Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMHJD7OAGV17", Request id "0HMHJD7OAGV17:00000004": An unhandled exception was thrown by the application.
      Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Request body too large. The max request body size is 30000000 bytes.
```

I tried this
`builder.WebHost.UseKestrel(options => options.Limits.MaxRequestBodySize = null);`

After the 'fix', it is working.

The documentation says: 28.6MB is the default
[MaxRequestBodySize](https://docs.microsoft.com/en-us/dotnet/api/Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerLimits.MaxRequestBodySize?view=aspnetcore-6.0&viewFallbackFrom=net-6.0)

**Comment by andycnguyen** [comment]
I seem to be experiencing the same, original issue. I'm testing with the `ExampleInvoice` solution, along with Previewer version 2022.11.0, and when I run the application the Preview window launches but never displays the pdf.

**Comment by justinobney** [comment]
I am having the same issue as @andycnguyen.
However, I was able to get it to work by installing version `2022.6.3` from NuGet and installing the `2022.6.0` version of the viewer.

`dotnet tool install questpdf.previewer --global --version 2022.6.0`

(I did not test any versions between 2022.6.0 & 2022.11.0)
