### ISSUE TITLE
PDF won't Generate in Azure Website

### ISSUE THREAD

**Issue by j-maldonado09** [QuestPDF/QuestPDF#390]
I just deployed my first .NET 6 website in Azure. In that website, there is a button to generate a PDF file dynamically using QuestPDF. When my app runs locally, the PDF is correctly generated creating the file under the main project folder. However, after deploying the website and running it on the server (http://azurewebsites.net/), I get an error in a popup window saying "Failed to receive the data". Using the developer tools (F12 in Chrome) in the Console tab I get a 500 internal server error. I asked in a Microsoft forum and they think that the issue might be that QuestPDF is not compatible with the Azure App service.
I will appreciate your feedback.

**Comment by MarcinZiabek** [comment]
QuestPDF is fully compatible with Azure App Services. 

Please try to capture the actual exception that is thrown on your Azure environment. If you are using development environment, asp.net returns exception message with HTTP response payload. However, in production environment, you will have pretty useless (on purpose) HTTP code 500 as in your case.

**Comment by j-maldonado09** [comment]
Thanks for the fast response. I am already in development environment. I will attach what I get as an error. Let me know if you would like more info
![1](https://user-images.githubusercontent.com/116769124/199601402-33f1f407-ed14-472d-8f1e-ed8ec890f86a.jpeg)

**Comment by pedroArriola** [comment]
I'm new to asp.net core (Razor Pages) and I just discovered this amazing library. I'm greatful to QuestPDF developers because this is the simplest solution I could find out there.

I think what j-maldonado09 is asking is what is the code o command that prompts the pdf to be downloaded to the user after being created. I have this question myself.  Sorry, English is my second language. 

Thanks in advance to the developers.

**Comment by JORGEMAL** [comment]
I asked for support in docs.microsoft.com forum and these are the 2 answers I have:

"Azure App Service isn't the local IIS environment you have, so you cannot expect the same code to work everywhere. Either you switch to your own Azure VM to host this web app, or you use a library that is compatible with Azure App Service (an open source project like QuestPDF is unlikely). You can ask the vendor of QuestPDF for more assistance"

--------------------------------------------------------------------------------------------------------------------------------------------

"All Azure Web Apps (as well as Mobile App/Services, WebJobs and Functions) run in a secure environment called a sandbox. Each app runs inside its own sandbox, isolating its execution from other instances on the same machine as well as providing an additional degree of security and privacy which would otherwise not be available.

Many Windows/.NET specific versions leverage IE APIs and therefore leverage User32/GDI32 extensively. These APIs are largely blocked in the sandbox (regardless of plan) and therefore these frameworks do not work in the sandbox.

Kindly see the supported and unsupported PDF generators on sandbox - [Azure Web App sandbox](https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox#unsupported-frameworks)"

So, this indicates that (most likely) QuestPDF is not Azure compatible.

Is this correct?

Regards.

**Comment by MarcinZiabek** [comment]
I am confident that QuestPDF is fully compatible with Azure. In fact, I am using this library in dozens of projects that generate thousands of PDF files a day. There is no problem here.

However, without exact exception that is thrown in your runtime, I am not able to help you. First, please catch the exception and provide its message with stacktrace 😁

**Comment by j-maldonado09** [comment]
The general error thrown is "cannot load or decode provided image". This message is only thrown when website is published in azure, I tried png and jpeg images.
The stack trace is shown in the attached image.
![QuestPDF error](https://user-images.githubusercontent.com/116769124/202532977-d9645881-34fa-4ed5-9137-82ceb62b9a82.png)

**Comment by MarcinZiabek** [comment]
Maybe that particular image file is broken?

**Comment by JORGEMAL** [comment]
Yes, we finally discovered that the problem is an image in the wrong location.
QuestPDF is fully compatible with Azure.

Thanks a lot for your support.
