### ISSUE TITLE
Get JSON structure that is sent to previewer to manually create a Document object

### ISSUE THREAD

**Issue by troncomputers** [QuestPDF/QuestPDF#585]
**Is your feature request related to a problem? Please describe.**
I am trying to create a PDF file, dynamically, based on an ERP system data. Mostly documents.

**Describe the solution you'd like**
I would like to pass a JSON (file or string) and create a PDF/Document object

**For example**
```C#
Document.CreateFromJson("json_here");
```

**Describe alternatives you've considered**
Self designed JSON structure that has issues with fluent interface design pattern

**Additional context**
I am generating a PDF file from JSON string, but I am not able to find perfect structure to handle it with Quest. You are doing something with JSON for the previewer here `Source/QuestPDF.Previewer/CommunicationService.cs`, method `HandleUpdatePreview`. Is there a chance that you would share how this JSON looks like? Would that work?

**Comment by MarcinZiabek** [comment]
I don't think that the Previewer-related capabilities will help you in any way. They mostly describe metadata and already rendered content.

Please use C# features such as loops and conditions to achieve dynamic structures. This way, you can use your data to alter the layout and content. 

In [this section](https://www.questpdf.com/getting-started.html#content-implementation) of the Getting Started tutorial, you may find a simple example of using the if-statement to show/hide the Comments message dynamically. 

Similarly, [this section](https://www.questpdf.com/getting-started.html#table-generation) uses a for-loop to generate rows for each item on the invoice.

I hope it helps 😁

**Comment by girlpunk** [comment]
@MarcinZiabek Had a thought, this may be useful when troubleshooting layout exceptions caused by user-generated content. It's sometimes difficult to get the actual content the user entered, but if some kind of blob could be generated that's enough to feed into the previewer (possibly with some extra helper code on either side) it may be rather handy in conjunction with #668

**Comment by MarcinZiabek** [comment]
@girlpunk, I agree! Over the last month, I have been exploring an inspector view for the next iteration of Previewer. It takes some time, as the effort is both about learning Flutter and exploring UI/UX designs. I plan to write a short article in the QuestPDF Companion discussion soon.

I foresee a tree-like view of the entire document's content, with additional metadata, etc.

<img width="496" alt="image" src="https://github.com/QuestPDF/QuestPDF/assets/9263853/c53e50fe-46d7-4375-9415-e972803f1ce1">

If there is a layout issue, clicking on the card will automatically expand the tree-view and redirect the user to a proper place in the document.

<img width="496" alt="image" src="https://github.com/QuestPDF/QuestPDF/assets/9263853/31e4f7ce-aa10-42c0-961d-7999406e47bb">

Next/next iteration would be to provide the reason of the issue, e.g., why the selected element does not fit in the available space. So, there are undoubtedly many ideas on how to improve the development lifecycle regarding layout issues. :)

**Comment by girlpunk** [comment]
Oh that looks very nice, though my thinking with this issue is where the error occurs in a production system and then needs the relevant metadata to recreate the issue in a development environment where tools like that can be used

**Comment by MarcinZiabek** [comment]
I see :) Technically, to display a document's structure with additional layout-debugging capabilities, I need to inject certain proxy elements to observe the rendering process. Then, all captured data is serialized and sent to the previewer. 

A similar technique could gather "snapshots" of layout issues from production environments. Then, such snapshot files could be opened in Previewer to explore the exact reasons. Or, if appropriately simplified, it could be presented as nicely formatted exceptions, e.g., in which method in the code the problem is present and why it occurs. 

I only fear that such techniques could degrade performance and easily generate tons of data in highly active production environments.

**Comment by MarcinZiabek** [comment]
However, before following this route, I think it is wise to investigate first ways of simplifying the debugging process, clearly communicating the layout problem, and lessening consequences on production environments (e.g. by allowing for content overflow). What do you think?
