### ISSUE TITLE
Lack of License Compatibility with Open Source Licenses

### ISSUE THREAD

**Issue by alastairlundy** [QuestPDF/QuestPDF#601]
Hi,
I didn't want to necro [this thread](https://github.com/QuestPDF/QuestPDF/issues/574) but the Licensing scheme used by this Software causes legal uncertainty in terms of compatibility/compliance with open source projects that rely on this.

It is not clear whether any open source project can use this project in its current form given the dynamic nature of the license (MIT for under 1 Million USD Annual Revenue or Enterprise License otherwise) because this makes this project no longer open source, it is source available. In theory most OSS projects are not themselves commercial in nature but other software that depends on them may be commercial in nature. It forces every project using this project to re-license their code and break compatibility with OSS licenses to accomodate the dynamic nature of this license. 

The descriptions for this library on GitHub, Nuget, and the Project's website seem confused as well since they say this project is Open Source when the license imposition makes this source available software and not open source.

@MarcinZiabek Are there any plans to enable this project to be compatible with open source projects?

If you want to implement a dual licensing scheme there are ways to do this whilst ensuring OSS users are not violating any licenses and you still get your revenue from businesses paying you to profit off of your work.

Examples of this include:
- Dual Licensing the project under GPLv3/AGPLv3 and a Proprietary License (Original MySQL model/Classic Dual License model) - Business customers pay to use the code under the proprietary license
- Offering Paid Support packages (Red Hat model) - Business customers pay to access support services associated with this project.
- Keeping the existing project Open Source (under an OSI compatible license) and developing a paid Premium version which adds a few extra features (Open Core Model) whilst still adding some new features to the OSS version - Businesses pay to access a premium version with premium paid features not found in the Open Source version.

If money is a serious concern or issue with any of the options I've mentioned above, I think you could stand to double or triple your paid license prices and not lose a significant amount of paying customers.

I look forward to your response and to what other OSS users of this project have to say if they wish to chime in.
Thanks

**Comment by MarcinZiabek** [comment]
Hi, thank you for presenting your thoughts in such a friendly manner 😁

> @MarcinZiabek Are there any plans to enable this project to be compatible with open source projects?

Licensing is certainly difficult, no doubt about it! I believe that the current license is already quite well compatible with OSS. Of course, [the License page](https://www.questpdf.com/license/) states general facts, but all details are described in [the License Selection Guide](https://www.questpdf.com/license/guide.html).

Generally speaking, there are multiple cases where the library can be used under the MIT license:
- every non-profit project (OSS, learning, articles, private projects),
- where your project uses a QuestPDF-dependent library (aka QuestPDF is a transitive dependency, opposite to a direct one), e.g. let's assume there is a tax library that uses QuestPDF to generate tax reports, and your application does not utilize QuestPDF API directly,
- all small businesses - while the business is under 1M USD annual gross revenue.

The abovementioned cases are also covered in [the License Survey](https://www.questpdf.com/license/survey.html).

So, if any open-source project uses the QuestPDF library, it uses it under the MIT license, and only that license should be followed.

> Examples of this include:
> 
> - Dual Licensing the project under GPLv3/AGPLv3 and a Proprietary License (Original MySQL model/Classic Dual License model) - Business customers pay to use the code under the proprietary license
> - Offering Paid Support packages (Red Hat model) - Business customers pay to access support services associated with this project.
> - Keeping the existing project Open Source (under an OSI compatible license) and developing a paid Premium version which adds a few extra features (Open Core Model) whilst still adding some new features to the OSS version - Businesses pay to access a premium version with premium paid features not found in the Open Source version.

I agree; those are also quite viable options. My idea was to provide a fully featured library to the vast majority of users completely for free, while trying to find funds with bigger companies. Premium features or copyleft licenses were against my vision. 

During discussions, a couple of members of the Community suggested that I may not be able to offer professional paid support, because I am only a single person. It makes much more sense to focus on library quality and documentation.

I hope companies will be more aware of OSS and willing to support them someday. In such a case, the entire idea of a dual-licensing model would be non-existing. Currently, the QuestPDF paid licenses cover around 30% of a median software developer's salary in US. At the same time, they are consistently 10 times (1000%) higher compared to my best GitHub Sponsors per month from 2022. This clearly shows that the OSS sponsorships do not work well (which is sad and raised countless of times). 

I am planning to prepare a general summary of this license transition, so other OSS developers will know what to expect. It was a rather difficult and complex process, even though I have many helpful and patient community members.

> If money is a serious concern or issue with any of the options I've mentioned above, I think you could stand to double or triple your paid license prices and not lose a significant amount of paying customers.

I don't think it is that simple, unfortunately. Once the library is paid for certain groups, it must compete with other commercial products. I am well aware that QuestPDF may do certain features much better (e.g., via its Fluent API, optimized layout engine, and better performance). However, it still misses a couple of features, and has areas that could be greatly improved.

> I look forward to your response and to what other OSS users of this project have to say if they wish to chime in.

I do not want to block the OSS usage, quite the opposite. I did my best to enable it to the fullest extent. Please let me know if you see any ways to improve the communication.

Best,
Marcin

**Comment by alastairlundy** [comment]
> where your project uses a QuestPDF-dependent library (aka QuestPDF is a transitive dependency, opposite to a direct one), e.g. let's assume there is a tax library that uses QuestPDF to generate tax reports, and your application does not utilize QuestPDF API directly,

Using the License Survey suggests that libraries or software directly dependant on QuestPDF would use it under the MIT license for Non Commercial Usage and Commercial Usage under 1 Million USD Annual Revenue. 

What's to stop non-direct dependants on QuestPDF from using a MIT licensed open source direct dependant library from not paying for a license? And if the non-direct dependant needs a license, how would this be enforced or handled? If the non-direct dependant needs a license due to it being a commercial product making over 1 Milliion USD Annual Revenue per year then then it breaks open source and the MIT license for the direct dependant.

> I agree; those are also quite viable options. My idea was to provide a fully featured library to the vast majority of users completely for free, while trying to find funds with bigger companies. Premium features or copyleft licenses were against my vision.

Have you considered the Business Source License? It seems to fit what you want. The Open Source Usage would be somwaht clearer because you could set the code to eventually become MIT license for each version after a certain period of time, whilst versions initially have the license that says they need to pay if they're making more than 1 Million USD Annual Revenue.

> I hope companies will be more aware of OSS and willing to support them someday. In such a case, the entire idea of a dual-licensing model would be non-existing. Currently, the QuestPDF paid licenses cover around 30% of a median software developer's salary in US. At the same time, they are consistently 10 times (1000%) higher compared to my best GitHub Sponsors per month from 2022. This clearly shows that the OSS sponsorships do not work well (which is sad and raised countless of times).

I think from a Corporate perspective it might be easier to get an expense approved for paying for a Software library or a support package for a library rather than Sponsoring the developer of a library they use. That could be part of why paying directly is more successful than the sponsorships.

I would say Sponsorships is probably a better mechanism for fans/individual supporters of a project to give money to a project than for Businesses.

> I don't think it is that simple, unfortunately. Once the library is paid for certain groups, it must compete with other commercial products. I am well aware that QuestPDF may do certain features much better (e.g., via its Fluent API, optimized layout engine, and better performance). However, it still misses a couple of features, and has areas that could be greatly improved.

I don't want to derail this thread or go too much off topic but I would recommend reading what Stripe has to say about B2B SaaS pricing (I understand this isn't SaaS but some of the principles can apply here).

One of the points they go over, which at first seems somewhat counter intuitive, the more money you charge the more understanding and less difficult B2B customers are to deal with. 

> I do not want to block the OSS usage, quite the opposite. I did my best to enable it to the fullest extent. Please let me know if you see any ways to improve the communication.

I'll have a think about it and if I think of anything I'll make another post in this thread.

**Comment by alastairlundy** [comment]
@MarcinZiabek  Any update on this question?

> What's to stop non-direct dependants on QuestPDF from using a MIT licensed open source direct dependant library from not paying for a license? And if the non-direct dependant needs a license, how would this be enforced or handled? If the non-direct dependant needs a license due to it being a commercial product making over 1 Milliion USD Annual Revenue per year then then it breaks open source and the MIT license for the direct dependant.

**Comment by MarcinZiabek** [comment]
I am sorry for the delayed response 😁 Recently, I am fighting with interoperability in C#...

> What's to stop non-direct dependants on QuestPDF from using a MIT licensed open source direct dependant library from not paying for a license? And if the non-direct dependant needs a license, how would this be enforced or handled? If the non-direct dependant needs a license due to it being a commercial product making over 1 Milliion USD Annual Revenue per year then then it breaks open source and the MIT license for the direct dependant.

You have certainly presented a couple of interesting corner cases. Generally speaking, if you are using the library indirectly (transitive dependency), you are following the MIT license; that's it - no strings attached. Personally, I doubt that the library will lose many customers. Realistically speaking, there are only a couple of [depending nuget libraries](https://www.nuget.org/packages/QuestPDF/#usedby-body-tab) using QuestPDF.

> Have you considered the Business Source License? It seems to fit what you want. The Open Source Usage would be somwaht clearer because you could set the code to eventually become MIT license for each version after a certain period of time, whilst versions initially have the license that says they need to pay if they're making more than 1 Million USD Annual Revenue.

This is certainly the option. But... every modern library should be built and published with symbols package. With tools like dotPeek (JetBrains, thank you!), nearly every nuget library is "open-source". I doubt there is much value for most companies in having access to code.

> I think from a Corporate perspective it might be easier to get an expense approved for paying for a Software library or a support package for a library rather than Sponsoring the developer of a library they use. That could be part of why paying directly is more successful than the sponsorships.

This is definitely a strong point. I want to experiment with it a little bit. However, promising prioritized support is a big responsibility. Especially since I may not be able to resolve certain cases immediately. So I need to be careful before publishing these statements.
