### ISSUE TITLE
Huge file size when using Chinese characters

### ISSUE THREAD

**Issue by seobjk** [QuestPDF/QuestPDF#662]
Hi,
I easily create the required PDF files with QuestPDF, which usually have a file size of 1.2 MB.
But when I have Chinese characters in the text, the file size is suddenly over 13 MB.
What can I do here to make the file size shrink back to a normal size? 
Does anyone have an idea?

The font is set using the following code:
  `page.DefaultTextStyle(TextStyle.Default.FontType("Times New Roman").Fallback(x => x.FontFamily("Microsoft YaHei")));`

Thanks, Greetings

**Comment by MarcinZiabek** [comment]
This behavior is due to including the entire Chinese font file within the output PDF file. This language consists of many glyphs, so the font file takes multiple megabytes. You may perform the manual font subsetting to reduce the number of glyphs to a known, estimated set. Or you can try to use another font, e.g. for simplified Chinese.

We are already prioritizing the automation of this process to completely mitigate this issue (large output PDF file size) as part of the following effort: https://github.com/QuestPDF/QuestPDF/discussions/622

**Comment by seobjk** [comment]
Thank you for the tip. I have incorporated a different, smaller font with Chinese characters using the Font Manager. While it didn't resolve the issue, the file size is now significantly smaller (6 MB instead of 13 MB).
