### ISSUE TITLE
GeneratePdf(stream) produces blank document

### ISSUE THREAD

**Issue by resignationinfinite** [QuestPDF/QuestPDF#683]
**Describe the bug**
When I use the overload of GeneratePDF() to save the PDF directly to a stream, the resulting file is empty. I have to save it to a byte array and then create a stream using that in order for it to work.

**To Reproduce**
```
using var output = new MemoryStream();
document.GeneratePdf(output);

return await fileService.SaveFileAsync(output, fileName, container);
```

**Expected behavior**
The Stream should contain the actual PDF.

**Comment by MarcinZiabek** [comment]
Hello, The `GeneratePdf` overload returning byte array does use stream internally ([code](https://github.com/QuestPDF/QuestPDF/blob/fb67379a8eb7e9e79abc9707042c3d5c3d5b540d/Source/QuestPDF/Fluent/GenerateExtensions.cs#L14C1-L22C10)). Maybe there is something wrong in you file service, e.g. stream is disposed too early?

**Comment by MarcinZiabek** [comment]
If you want to use the CopyToAsync function, please make sure that the stream is rewinded to the very beginning:

```csharp
using (FileStream fs = new(localPath, FileMode.Create))
{
    stream.Position = 0; // <- here
    await stream.CopyToAsync(fs);
}
```

However, your approach does not make sense (has no benefits). When using the MemoryStream, you will first load the entire PDF document into memory and then write it all at once to the file.

A proper / memory-friendly approach is to stream directly to the file, like so:

```csharp
using (var fs = new FileStream("output.pdf", FileMode.Create))
{
    document.GeneratePdf(fs);
}
```

**Comment by MarcinZiabek** [comment]
Well, one of the primary reasons for using streams is saving memory. However, MemoryStream is a special case: when you write to this stream synchronously (first populate, then consume), it acts as a byte array.

As long as your PDF documents are rather small in size, or you are generating them infrequently, it doesn't really matter.

Also, please be aware that QuestPDF may start writing to the stream but somewhere during document generation logic, the exception can be thrown. Therefore, saving data to a temporary location (MemoryStream, temporary file) is usually good idea, instead of streaming directly to blob storage.
