### ISSUE TITLE
Docker with no fontmanager failing CompatibilityChecker

### ISSUE THREAD

**Issue by Ziirf** [QuestPDF/QuestPDF#700]
We are running a docker container with no native font manager, and it have been running fine, but since we updated QuestPDF from 2023.6.1 to 2023.10.1, our container stopped working, due to failing NativeDependencyCompatibilityChecker. this is happening when we try to load the license as the first thing.

It worked completely fine before the update, and we are loading in fonts manually through the QuestPDF font manager later.
QuestPDF v2023.10.1
SkiaSharp.NativeAssets.Linux.NoDependencies v2.88.6
HarfBuzzSharp.NativeAssets.Linux v7.3.0

![image](https://github.com/QuestPDF/QuestPDF/assets/49737643/b547a060-6644-49f1-8371-a00758cb286b)

**Comment by Ziirf** [comment]
This issue is related to #687 this is most, I can confirm that SkiaSharp.SKTypeface.Default is null, due to no having a font manager on the image.
I can't seem to find a way to circumvent the SkiaSharp.SKTypeface.Default not being null.

**Comment by MarcinZiabek** [comment]
Thank you for reaching out. This problem is likely related to the SkiaSharp update (2.88.3 -> 2.88.6) - maybe they have changed the way of loading native dependency files. 

The exception mentions two nuget packages. Would you please ensure that they are explicitly added to your primary/startup project? (assuming similarity to https://github.com/QuestPDF/QuestPDF/issues/694#issuecomment-1799384202)

**Comment by Ziirf** [comment]
The change is regarding the NativeDependencyCompatibilityChecker.test() which is checking on SkiaSharp.SKTypeface.Default, which will be null if you do not have a font manager installed on the docker image.
As we are loading in the fonts manually through the QuestPDF font manager, the lack of fonts in SkiaSharp, have not been an issue for us previously. It is only a problem due to this new NativeDependencyCompatibilityChecker.test(), that have been introduced in the latest version.

We have rolled back to a previous version of QuestPDF, while we waiting for a way in which this is resolved.
[Docker Image link](https://github.com/dotnet/dotnet-docker/blob/a8e1aa17ed5cac5a0ed613285cbaaee9e133e6ac/src/aspnet/7.0/bullseye-slim/amd64/Dockerfile)

**Comment by sandi91** [comment]
Hey everyone. We have just found the fix for the problem in our local Docker container which is referencing the latest QuestPDF 2023.10.1, the issue was indeed in missing fonts, and the fix for our alpine based docker image was adding these packages:

RUN apk --no-cache add msttcorefonts-installer fontconfig && \
    update-ms-fonts && \
    fc-cache -f

Hope this helps you!!

**Comment by MarcinZiabek** [comment]
@sandi91 Thank you so much for sharing this information. If the problem is related to the OS font manager, fixing the issue should be relatively straightforward. The `NativeDependencyCompatibilityChecker` class aims to call any APIs from SkiaSharp and HarfBuzzSharp, which trigger loading native dependencies.

Changing the code to use `SkPaint` and `HarfBuzzSharp.Buffer` should be sufficient:

```csharp
private static Exception? CheckIfExceptionIsThrownWhenLoadingNativeDependencies()
{
    try
    {
        // accessing any SkiaSharp object triggers loading of SkiaSharp-related DLL dependency
        using var typeface = new SKPaint();

        // accessing any HarfBuzzSharp object triggers loading of HarfBuzz-related DLL dependency
        using var shaper = new HarfBuzzSharp.Buffer();

        // everything loads and works correctly
        return null;
    }
    catch (Exception exception)
    {
        return exception;
    }
}
```

**Comment by sandi91** [comment]
We would also suggest returning back different error messages. Because the exception was caught because of the typeface is null issue, but the error is misleading to nuget packages when in fact all 3 nuget packages were directly referenced in a project, adding them to the startup project didn't help at all and we had to spend some time for this. 

maybe this is a bad idea to ask it here, but anyway.. We have a process which is updating our nuget packages every single night. and it is always trying to get this version - https://www.nuget.org/packages/QuestPDF/2202.8.2. even tho it's deprecated the updater is getting it from the list of QuestPDF versions. Could you get rid of that version somehow? or change the versioning from date to something bigger than 2202 so the updates work as expected and we dont create workarounds? :)

**Comment by MarcinZiabek** [comment]
> We would also suggest returning back different error messages. Because the exception was caught because of the typeface is null issue, but the error is misleading to nuget packages when in fact all 3 nuget packages were directly referenced in a project, adding them to the startup project didn't help at all and we had to spend some time for this.

It is just a little bit unfortunate that `SkTypeface.Default` does not work according to the specification when font manager is not present in the runtime OS, it should never be null (https://learn.microsoft.com/en-us/dotnet/api/skiasharp.sktypeface.default?view=skiasharp-2.88#remarks). As mentioned in my previous comment, I will change the code to use different SkiaSharp object. This should help :)

> maybe this is a bad idea to ask it here, but anyway.. We have a process which is updating our nuget packages every single night. and it is always trying to get this version - https://www.nuget.org/packages/QuestPDF/2202.8.2. even tho it's deprecated, the updater is getting it from the list of QuestPDF versions. Could you get rid of that version somehow? or change the versioning from date to something bigger than 2202 so the updates work as expected, and we don't create workarounds? :)

Would you please check if there is any cache in your build system / private feed? I have already marked the package as deprecated and hidden. However, every package pushed to the Nuget platform is immutable; it cannot be removed/updated in any way.

If I am not aware of some options, please let me know. I would really like to remove this old package!

**Comment by sandi91** [comment]
Ok it's clear about the "Check of the dependecies". Thanks for that.
I think we hijacked a bit the topic here, but maybe our fix will even temporarily work for the author here :)

So on the nuget package - we are using self hosted VMs for the builds and they are replaced every night, so there is no cache. I have checked and it is received in this URL - https://api.nuget.org/v3/registration5-gz-semver2/questpdf/index.json. if you search here you will find that 2202... version. I have read the documentation and it seems the Delete=Unlist only. They unlist it from the search and what not, but they dont hard delete it. Which makes sense, there might be people using that in their projects, the hard deletion would block all those people. Seems the only fix might be go with some 2203.11.10 or 2223.11.10 :)

**Comment by Ziirf** [comment]
> I think we hijacked a bit the topic here, but maybe our fix will even temporarily work for the author here :)
We were not able to use the fontconfig, even though we knew it would most likely solve the problem. I am just happy that the issue have been solved this quickly. I am currently not at work, but as soon as I return I will try to update and see if everything works, and then close this issue.

I did notice a small thing in the update notes notes, not that it will impact performance at all, but I still wanted to let you know.
You changed the functions that the helper method called, but seem to have forgotten the variable names.
```cs
// accessing any SkiaSharp object triggers loading of SkiaSharp-related DLL dependency
using var typeface = new SkiaSharp.SKPaint();

// accessing any HarfBuzzSharp object triggers loading of HarfBuzz-related DLL dependency
using var shaper = new HarfBuzzSharp.Buffer();
```

And again, thanks for the quick update. 👍

**Comment by Ziirf** [comment]
Been able to test this morning, and can see it now works.
So I am closing the issue. 👍
