### ISSUE TITLE
Last line of a table not rendered

### ISSUE THREAD

**Issue by crabouif** [QuestPDF/QuestPDF#767]
Hello,
Again thanks for the great job!

I'm facing to a strange issue. In a special invoice, I'm rendering a table for bill lines, but in some cases the last line is not rendered.
I guess (in my feeling) the preceding line do a wrap of long text and maybe it's related.

I found a hack that resolve the issue waiting a fix, but it's not clean and I'm not sure it's stable...

**To Reproduce**
I did a solution that reproduce it. But I can't attach it here due to code I want to keep secret.
But it's OK to send it in a private channel.

For the hack, search in my solution code in file `QuestPDF-line-issue/InsuranceProof/v45/InsuranceProof45Document.cs` the comment `// Here is a hack to show all lines`.

**Expected behavior**
All lines should be rendered.

**Screenshots**
Issue:
![image](https://github.com/QuestPDF/QuestPDF/assets/13976717/0507eac9-1198-41d1-907c-774b155fde6f)

What should be (with the hack):
![image](https://github.com/QuestPDF/QuestPDF/assets/13976717/6db37199-6525-4771-8f8d-6ca47ef1e153)

**Environment**
What version of the library do you use? 
* QuestPDF 2023.12.4
* SkiaSharp.NativeAssets.Linux.NoDependencies 2.88.7
* HarfBuzzSharp.NativeAssets.Linux 7.3.0.1

What operating system do you use? (OS type, x64 vs x86 vs arm64):
* I'm working on Linux Mint x64 and my prod server is a Debian x64.

**Comment by MarcinZiabek** [comment]
Hello 😄 

I am sorry for replying so late. Would you please send your code to contact@questpdf.com ?

**Comment by MarcinZiabek** [comment]
I have finally found some time to investigate this issue.

The problem was not in the QuestPDF library per se but in the implementation of the dynamic table (with sub-total values). The root cause was related to the floating-point number calculation. A genuinely mind-bending issue :)

As the code was based on the official example, I have updated the documentation to cover necessary adjustments: https://github.com/QuestPDF/QuestPDF-Documentation/commit/2e09358a2cf37e6289bd855b067b8737eecf6f70
