### ISSUE TITLE
[HELP] Implicit white space when font size increases

### ISSUE THREAD

**Issue by lehanEngelbrecht** [QuestPDF/QuestPDF#810]
I am trying to create retail shelf labels, but my only issue is that there is a implicit padding when I increase the font size and I would thus like to get rid of the implicit padding since the text below the value should be 'closer' to the larger text above it. Please see both pictures attached for as reference to my current code and the generated pdf. (Please not my code is in F# but it is basically the same as C#)
<img width="958" alt="Screenshot 2024-03-07 at 09 33 21" src="https://github.com/QuestPDF/QuestPDF/assets/151817644/f0152fa8-ad06-4277-94a3-9c6088cb0fc0">
<img width="155" alt="Screenshot 2024-03-07 at 09 37 15" src="https://github.com/QuestPDF/QuestPDF/assets/151817644/cbb4693e-6490-4d4b-a6cb-b946089160c4">

**Comment by girlpunk** [comment]
I haven't recreated your layout, however this is likely because vertical space is reserved for characters that extend above and below the baseline. As a workaround, you could apply some negative top padding to the second line of text, however note that this may cause unexpected overlaps with some text
