### ISSUE TITLE
Lato font is not included in platform-specific builds

### ISSUE THREAD

**Issue by xackus** [QuestPDF/QuestPDF#859]
**Describe the bug**
Lato font is not included in platform-specific builds (not in `runtimes` and not directly in the publish directory).
In cross-platform builds it's included in `runtimes/any/native`.

**To Reproduce**
Publish to a folder with a set `RuntimeIdentifier` (for example `win-x64`).

**Expected behavior**
The font is included.

**Environment**
What version of the library do you use? 2024.3.1
What operating system do you use? win-x64, linux-x64

**Additional context**
I don't think MSBuild recognizes `runtimes/any/native`.
It's probably best to put the font outside of the `runtimes` directory, since it's not platform specific.

BTW: Great library, my company is planning to purchase a license.

**Comment by MarcinZiabek** [comment]
Thank you for reporting this issue 😄

I have further investigated the problem and followed your suggestion. The Lato font is no longer provided within the `runtimes/any/native` folder, rather than included in the nuget package as a resource and then copied by a specialized `.targets` file. Honestly, the nuget platform is not very developer-friendly in terms of creating those packages. Sometimes, it seems to be overcomplicated.

Would you please test the newest 2024.3.2 version? https://github.com/QuestPDF/QuestPDF/releases/tag/2024.3.2

**Comment by xackus** [comment]
It works now. Thanks for fixing it so quickly.
